### ISSUE TITLE
New to the ETH business - what is the easiest way to run the code in the examples?

### ISSUE THREAD

**Issue by stefek99** [raineorshine/solidity-by-example#5]
Deployed here: https://ropsten.etherscan.io/address/0x311fabae9000f246cf34ac47ff3de76ebaa3609a#code

_(via Remix and Metamask)_

Put address and ABI into MEW:

![image](https://user-images.githubusercontent.com/249703/33224414-24d7ed7c-d161-11e7-983e-a1dce0edec7b.png)

Via Ethereum Wallet:

![image](https://user-images.githubusercontent.com/249703/33224573-e3ef4ee8-d162-11e7-948f-93cc520efbdc.png)

# Is there a magic button to run the thing?

**Comment by stefek99** [comment]
Tried deploying to `testrpc` via `truffle`

```
var ArrayDelete = artifacts.require("./ArrayDelete.sol");
module.exports = function(deployer) {
  deployer.deploy(ArrayDelete);
};

```

```
truffle console
ArrayDelete = ArrayDelete.deployed()
ArrayDelete.then(function(instance) { result = instance.main(); })
result
```

```
{ tx: '0x73c752c4b31c22bc2fe99697cd1189682af346fb0edd69527327e037cabf72b9',
  receipt:
   { transactionHash: '0x73c752c4b31c22bc2fe99697cd1189682af346fb0edd69527327e037cabf72b9',
     transactionIndex: 0,
     blockHash: '0x665c969bc036271ec2be6bfb14b99551f19a6b185e1e8a313e108669dacfa152',
     blockNumber: 41,
     gasUsed: 175082,
     cumulativeGasUsed: 175082,
     contractAddress: null,
     logs: [] },
  logs: [] }
```

Surely there is an easy way...

**Comment by stefek99** [comment]
Tried running with command line:

```
solcjs ArrayDelete.sol
Invalid option selected, must specify either --bin or --abi
```

**Comment by stefek99** [comment]
Remix IDE, surely there must be some easy option to run an example code:

![image](https://user-images.githubusercontent.com/249703/33230025-0c2bfdfa-d1d3-11e7-8645-ce42ac87710e.png)

**Comment by raineorshine** [comment]
Hi! The code examples can easily be run in Remix. It looks like you are on the right track?

1. Paste in contract code
2. Click the `Create` button to deploy the contract
3. Click the different function buttons to call functions and see the results.

**Comment by stefek99** [comment]
That was insanely easy, once you know it. Just like Apple root hack.

![image](https://user-images.githubusercontent.com/249703/33402071-5ab3a616-d553-11e7-85f4-d997bf130dd1.png)

Maybe you'll know?

**Comment by raineorshine** [comment]
Great!

It depends on which instance of `A` you are asking about. There is no way to access the `A` that is created with `makeA` because it is only a local variable (not `storage`).

It is possible to deploy `A` directly though. You just have to select `A` under the dropdown menu (the first arrow in your last screenshot attached to "deployed manager"). Then the "Create" button will

**Comment by stefek99** [comment]
One of the examples included `Manager` and `A`, I was wondering what is happening under the hood - can I access `A` if it was deployed via `Manager`…

Hope @quazia wouldn't mind, posting from one public channel to another:

> The easiest way I've found to do it is with event logging, log an event on creation of the sub-contract you're trying to interact with, go on etherscan or use another solution to monitor events, and then pull the address of the created contract that way. Once you have the address of the contract, it's source code, and presumably it's ABI you should be able to interact with it in a few ways

> You could set a variable with the most recently created `A` or something and then just check the variable or create some sort of data structure with all `A`'s created or something but events and event retrieval is almost certainly the best approach here.

**Comment by raineorshine** [comment]
Ah, good point. It is a regular contract still so you can interact with it via its ABI. The `Manager` contract stores the address of `A`. If you get the `address`, you can interact with it like any contract.

**Comment by stefek99** [comment]
Related: https://ethereum.stackexchange.com/questions/2835/how-to-quickly-test-a-solidity-function

**Comment by stefek99** [comment]
WOW: https://ethfiddle.com/

*(exactly what I've been looking for)*
